(ns x25519.differential-test
  "This implementation against BouncyCastle's, plus the two RFC 7748 vectors
  that are too slow for a suite people run on every change.

  A separate source root reached only by the `:oracle` alias, because
  BouncyCastle must never become a dependency of this library: it is what the
  library is CHECKED AGAINST, not something it builds on.

      clojure -M:oracle

  The scalars and u-coordinates are generated by a fixed LCG, not a random
  source. A differential test that picks new inputs each run reports a
  failure nobody can reproduce, which is worse than one that never fires."
  (:require [clojure.test :refer [deftest is testing]]
            [x25519.core :as x])
  (:import (org.bouncycastle.math.ec.rfc7748 X25519)))

(defn- ba [v] (byte-array (map unchecked-byte v)))

(defn bouncycastle [scalar u]
  (let [out (byte-array 32)]
    (X25519/scalarMult (ba scalar) 0 (ba u) 0 out 0)
    (x/hex out)))

(defn bouncycastle-base [scalar]
  (let [out (byte-array 32)]
    (X25519/scalarMultBase (ba scalar) 0 out 0)
    (x/hex out)))

(defn- lcg
  "A fixed byte sequence. `unchecked-*` because a 64-bit LCG is defined by its
  wraparound and Clojure's checked arithmetic throws on exactly that."
  [seed n]
  (->> (iterate (fn [v] (unchecked-add (unchecked-multiply v 6364136223846793005)
                                       1442695040888963407))
                (long seed))
       (drop 1) (take n)
       (mapv #(bit-and (unsigned-bit-shift-right % 24) 0xFF))))

(deftest agrees-with-bouncycastle
  (let [cases (for [i (range 40)] [(lcg (+ 1000 i) 32) (lcg (+ 7000 i) 32)])]
    (is (= 40 (count cases)))
    (doseq [[k u] cases]
      (is (= (bouncycastle k u) (x/hex (x/x25519! k u)))
          (str "scalar " (subs (x/hex k) 0 8) "… u " (subs (x/hex u) 0 8) "…")))))

(deftest agrees-on-the-base-point
  (doseq [i (range 20)]
    (let [k (lcg (+ 300 i) 32)]
      (is (= (bouncycastle-base k) (x/hex (x/public-key k)))
          (str "public-key " (subs (x/hex k) 0 8) "…")))))

(deftest the-oracle-can-fail
  (testing "a differential test that cannot report a difference proves nothing"
    (let [k (lcg 1 32) u (lcg 2 32)]
      (is (not= (bouncycastle k u) (bouncycastle (lcg 3 32) u))
          "BouncyCastle must distinguish two scalars, or the comparisons above are vacuous"))))

(deftest rfc-7748-iterated-one-thousand
  ;; §5.2's thousand-round value. About 76 ms per scalar multiplication, so
  ;; over a minute -- which is why it lives here and not in the fast suite.
  (let [nine (x/hex x/base-point)]
    (loop [k nine u nine i 0]
      (if (= i 1000)
        (is (= "684cf59ba83309552800ef566f2f4d3c1c3887c49360e3875f2eb94d99532c51" k))
        (recur (x/hex (x/x25519! (x/unhex k) (x/unhex u))) k (inc i))))))
